apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      name: postgres
  # there can be only one pod at a time because of the persistent volume claim
  strategy:
    type: Recreate
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: hmaksqaacr.azurecr.io/hm-products:postgres
#          volumeMounts:
#            - mountPath: '/data'
#              name: lhci-data-volume
#          # required for ingress health checks to work
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres
  type: NodePort