# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: 
  - lighthouse/$(appName)
 # - main

pool: LHCI

variables:
- name: LHCI_BUILD_CONTEXT__CURRENT_BRANCH
  value: "$(Build.SourceBranch)" 

stages:
  - stage: ClientSidePerformanceProfiling
    displayName: "Client Side Performance Profiling"
    # variables:
    #       LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$(Build.SourceBranch)"
    jobs:
      - job: ExecuteLighthouseProfiling
        displayName: "Execute Lighthouse Profiling"
        steps:
          - checkout: "self"
            fetchDepth: 1
          - task: Npm@1
            displayName: "Install NPM"
            inputs:
               command: "install"
               workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
          - task: Npm@1
            displayName: "Run Healthcheck"
            inputs:
               command: "custom"
               workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
               customCommand: "run healthcheck"
          - task: Npm@1
            displayName: "Execute Performance Profiling"
            inputs:
              command: "custom"
              workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
              customCommand: "run collect" 
  - stage: UploadPerformanceReport
    displayName: "Upload Performance Report"
    jobs:
      - job: UploadPerformanceReport
        displayName: "Upload Performance Report"
        steps:
          - checkout: none
          - task: Npm@1
            displayName: "Upload Performance Report"
            inputs:
              command: "custom"
              workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
              customCommand: "run Upload"
  - stage: Assertions
    displayName: "Perform Assertions"
    jobs:
      - job: PerformAssertions
        steps:
          - checkout: none
          - task: Npm@1
            displayName: "Perform Assertions"
            inputs:
              command: "custom"
              workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
              customCommand: "run assert"


