FROM node:12-buster-slim

WORKDIR /usr/src/lhci
COPY package.json .
COPY lighthouserc.json .
RUN npm install
ENV LHCI_STORAGE__SQL_DIALECT="postgres"
ENV LHCI_STORAGE__SQL_CONNECTION_URL="postgresql://postgres:password@postgres:5432/postgres"

RUN npm install -g @lhci/cli

EXPOSE 9001
CMD [ "npm", "start" ]
