# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest
  # name: Default
  # demands:
  #   - agent.name -equals windows-agent

stages:
  - stage: build
    displayName: "Build / Deploy"
    jobs:
      - job: runBuild
        displayName: "Run Build"
        steps:
          - script: "echo building..."
  - stage: deploy
    displayName: "Deploy"
    dependsOn: build
    jobs:
      - job: runDeploymnet
        displayName: "Run Deployment"
        steps:
          - script: "echo deploying..."
  - stage: ClientSidePerformanceProfiling
    displayName: "Client Side Performance Profiling"
    jobs:
      - job: runLighthouseTest
        displayName: "Execute Lighthouse"
        variables:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$(Build.SourceBranch)"
        steps:
          - checkout: "self"
            fetchDepth: 1
          - task: Npm@1
            inputs:
              command: "install"
          - task: Npm@1
            displayName: "Healthcheck"
            inputs:
              command: "custom"
              customCommand: "run lh:healthcheck"
             - task: Npm@1
            displayName: "Execute Performance Profiling"
            inputs:
              command: "custom"
              workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
              customCommand: "run collect" 
  - stage: UploadPerformanceReport
    displayName: "Upload Performance Report"
    jobs:
      - job: UploadPerformanceReport
        displayName: "Upload Performance Report"
        steps:
          - checkout: none
          - task: Npm@1
            displayName: "Upload Performance Report"
            inputs:
              command: "custom"
              workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
              customCommand: "run Upload"
  - stage: Assertions
    displayName: "Perform Assertions"
    jobs:
      - job: PerformAssertions
        steps:
          - checkout: none
          - task: Npm@1
            displayName: "Perform Assertions"
            inputs:
              command: "custom"
              workingDir: '$(Build.SourcesDirectory)/devops-tools/lighthouse/$(appName)'
              customCommand: "run assert"
