# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest
  # name: Default
  # demands:
  #   - agent.name -equals windows-agent

stages:
  - stage: build
    displayName: "Build / Deploy"
    jobs:
      - job: runBuild
        displayName: "Run Build"
        steps:
          - script: "echo building..."
  - stage: deploy
    displayName: "Deploy"
    dependsOn: build
    jobs:
      - job: runDeploymnet
        displayName: "Run Deployment"
        steps:
          - script: "echo deploying..."
  - stage: ClientSidePerformanceProfiling
    displayName: "Client Side Performance Profiling"
    jobs:
      - job: runLighthouseTest
        displayName: "Execute Lighthouse"
        variables:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$(Build.SourceBranch)"
        steps:
          - checkout: "self"
            fetchDepth: 1
          - task: Npm@1
            inputs:
              command: "install"
          - task: Npm@1
            displayName: "Healthcheck"
            inputs:
              command: "custom"
              customCommand: "run lh:healthcheck"
